params ["_veh"];

if (!isServer) exitWith {};
_cargo = ["U_C_Journalist","U_C_Poloshirt_blue","U_C_Poloshirt_burgund","U_C_Poloshirt_salmon","U_C_Poloshirt_stripped","U_C_Poloshirt_tricolour","U_C_Poor_1","U_C_Poor_2","U_C_Poor_shorts_1","FirstAidKit","HandGrenade_Stone","HandGrenade","MiniGrenade","SmokeShell","SmokeShellYellow","SmokeShellGreen","SmokeShellRed","SmokeShellPurple","SmokeShellOrange","SmokeShellBlue","Chemlight_green","Chemlight_red","Chemlight_yellow","Chemlight_blue","B_IR_Grenade","O_IR_Grenade","I_IR_Grenade","10Rnd_762x54_Mag","20Rnd_762x51_Mag","9Rnd_45ACP_Mag","16Rnd_9x21_Mag","6Rnd_45ACP_Cylinder","30Rnd_9x21_Mag","30Rnd_65x39_caseless_green","30Rnd_556x45_Stanag","30Rnd_556x45_Stanag_Tracer_Red","30Rnd_556x45_Stanag_Tracer_Green","30Rnd_556x45_Stanag_Tracer_Yellow","30Rnd_556x45_Stanag_red","30Rnd_556x45_Stanag_green","30Rnd_65x39_caseless_mag","hgun_P07_F","hgun_ACPC2_F","hgun_Rook40_F","hgun_Pistol_heavy_02_F"] call BIS_fnc_selectRandom;
_gun = ["arifle_MX_F", "arifle_MX_GL_Black_F"] call BIS_fnc_selectRandom;
//_RandomLight = ["_veh setPilotLight true;","_veh setCollisionLight true;"] call BIS_fnc_selectRandom;
if (isServer) then {
	_veh enableDynamicSimulation false;
	clearWeaponCargoGlobal _veh;
	clearMagazineCargoGlobal _veh; 
	clearItemCargoGlobal _veh;
	clearBackpackCargoGlobal _veh;
	_veh addItemCargoGlobal [_cargo, 1];
	_veh setPilotLight true;
	_veh setCollisionLight true;
	//_veh animate ["BeaconsStart", 1]
	//_veh engineOn true;
	//vehicle player setHitPointDamage ["hitFuel", 0 + random 1];
	//vehicle player setHitPointDamage ["hitFuel", 1];
	//vehicle player setHitPointDamage ["hitFuel2", 1];
	_veh setFuel (0 + random 0.99);
	_veh setVehicleAmmo (0 + random 0.99);
	_veh setHitPointDamage ["hitEngine", 0 + random 1];
	_veh setHitPointDamage ["hitEngine2", 0 + random 1];
	_veh setHitPointDamage ["hitFuel", 0 + random 1];
	_veh setHitPointDamage ["hitFuel2", 0 + random 1];
	_veh setHitPointDamage ["HitHall", 0 + random 0.9];
	_veh setHitPointDamage ["HitLAileron", 0 + random 1];
	_veh setHitPointDamage ["HitRAileron", 0 + random 1];
	_veh setHitPointDamage ["HitLCElevator", 0 + random 1];
	_veh setHitPointDamage ["HitRElevator", 0 + random 1];
	_veh setHitPointDamage ["HitLCRudder", 0 + random 1];
	_veh setHitPointDamage ["HitRRudder", 0 + random 1];
	_veh setHitPointDamage ["HitAvionics", 0 + random 1];
	_veh setHitPointDamage ["HitLTrack", 0 + random 1];
	_veh setHitPointDamage ["HitRTrack", 0 + random 1];
	_veh setHitPointDamage ["HitTurret", 0 + random 1];
	_veh setHitPointDamage ["HitGun", 0 + random 1];
	_veh setHitPointDamage ["HitHRotor", 0 + random 1];
	_veh setHitPointDamage ["HitVRotor", 0 + random 1];
	_veh setHitPointDamage ["HitGlass1", 0 + random 0.99];
	_veh setHitPointDamage ["HitGlass2", 0 + random 0.99];
	_veh setHitPointDamage ["HitGlass3", 0 + random 0.99];
	_veh setHitPointDamage ["HitGlass4", 0 + random 0.99];
	_veh setHitPointDamage ["HitGlass5", 0 + random 0.99];
	_veh setHitPointDamage ["HitGlass6", 0 + random 0.99];
	_veh setHitPointDamage ["HitLFWheel", 0 + random 1];
	_veh setHitPointDamage ["HitLBWheel", 0 + random 1];
	_veh setHitPointDamage ["HitRFWheel", 0 + random 1];
	_veh setHitPointDamage ["HitRBWheel", 0 + random 1];
	_veh setHitPointDamage ["HitRMWheel", 0 + random 1];
	_veh setHitPointDamage ["HitLMWheel", 0 + random 1];
	//_veh setRepairCargo [0 + random 1];
	//_veh setFuelCargo [0 + random 1];
	//_veh setAmmoCargo [0 + random 1];
	//_veh landAt [0 + random 5];
	//_allAirports = allAirports;
	_veh disableTIEquipment true;
	_veh disableNVGEquipment true;
	//[_veh] call BIS_fnc_AircraftFoldingWings
	_veh addEventHandler ["Hit",{["play", _this select 0] call BIS_fnc_carAlarm;}];
	_veh addEventHandler ["IncomingMissile", {[_this select 0,"SmokeLauncher"] call BIS_fnc_fire;}];
	_veh enableDynamicSimulation true;
};